### ISSUE TITLE
Got unpleasant result on ScanNetV2 scene0084_00

### ISSUE THREAD

**Issue by Timber-Ye** [botaoye/S3PRecon#4]
Hi, thanks for a great job! I'm running the code to reconstruct scene0084_00 (one-eighth of views are uniformly sampled for reconstruction, no changes in config files), but to get unsatisfactory results (as shown below).
![S3PRecon-scene0084_00](https://github.com/botaoye/S3PRecon/assets/46010859/952965a0-277f-4b18-a827-65ef48fd6762)

I got the `depth_colmap` with the exact code from [ManhattanSDF](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/run_colmap/run.py). Here is the dense reconstruction result:
![COLMAP-scene0084_00](https://github.com/botaoye/S3PRecon/assets/46010859/8802d987-4fb3-4172-8c36-d21cf5756682)

I also got a seemingly more decent result by ManhattanSDF with the same COLMAP outputs:
![ManhattanSDF-scene0084_00](https://github.com/botaoye/S3PRecon/assets/46010859/c791d74d-e9fa-4058-8a45-e5466e9093f5)

I'm probably running the code in a wrong way, but having difficulty figuring out. Any advice or insight on such issue would be highly appreciated!

**Comment by DecaYale** [comment]
@Timber-Ye Did you solve it?

**Comment by Timber-Ye** [comment]
No, I didn't :(
